services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bumchu2004
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: bumchu2004
      DB_NAME: todo_db
      DB_SSL: false
      FRONTEND_URL: "*"
    depends_on:
      db:
        condition: service_healthy    # ← waits until DB is ready

volumes:
  pgdata: